### PR TITLE
Enh support tf216 keras3

### LINKED ISSUE #3645: BUG: 'tuple' object has no attribute 'as_list'
### Issue Description

I used shap to interpret my cnn model. When shap tries to get the output shape in its internal function, i get error. **I know it's because of the tensorflow version**, how can I fix this error?
**There isn't problem in tensorflow==2.15.0
Please solve this problem for tensorflow==2.16.1**

### Minimal Reproducible Example

```python
import shap
explainer = shap.DeepExplainer(model=model, data = X_train[0:10])
shap_values = explainer.shap_values(X_test[0:10])
```

### Traceback

```shell
AttributeError
Traceback (most recent call last)
<ipython-input-9-5d9f53dcf3ce> in <cell line: 1>()
----> 1 explainer = shap.DeepExplainer(model=model, data = X_train[0:10])
      2 shap_values = explainer.shap_values(X_test[0:10])
1 frames
/usr/local/lib/python3.10/dist-packages/shap/explainers/_deep/deep_tf.
py in __init__(self, model, data, 
session, learning_phase_flags)
    170             self.phi_symbolics = [None]
    171         else:
--> 172             noutputs = self.model_output.shape.as_list()[1]
    173             if noutputs is not None:
    174                 self.phi_symbolics = [None for i in range(noutputs)]

AttributeError: 'tuple' object has no attribute 'as_list'
```

### Expected Behavior

_No response_

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

my package versions:
tensorflow==2.16.1
shap==0.45.1

### PR DESCRIPTION
**Pull request by CloseChoice**
## Overview

Closes #3645 

Description of the changes proposed in this pull request:
 - updated tests to work with keras3 + tensorflow 2.16

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [x] Unit tests added (if fixing a bug or adding a new feature)

### CODE REVIEW

**Comment by CloseChoice** [comment]
@connortann : I remember we had this error before while package installation:

```bash
 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 d7599b65c7af7abbc978dbf345712c60fd596aa5670496561cc10e8a71cebfb2
             Got        1f3afff1ebaea3408018256dccf958cd167e3815cfab29253155063ee7ac51c5
```
What was the solution? Removing the current caches? 

On a side note: do we have more than 10GB cache size: https://github.com/shap/shap/actions/caches (see `Approaching total cache storage limit (14.48 GB of 10 GB Used)`)?

**Comment by connortann** [comment]
As I recall, that issue was just a transient network issue. Re-running the CI job seemed to fix the issue and the downloaded packages matched the expected hashes.

Regarding cache size, yes I think we might approach or occasionally exceed that limit. I remember doing a fair bit of trial-and-error trying to determine which packages could be cached by pip on CI, without exceeding the total limit. My notes from that experimentation are here:

https://github.com/dsgibbons/shap/issues/42#issuecomment-1571735472

As per that thread, we decided to cache only a couple of packages, aiming to keep each cache under 2GB total so that the total 10GB cache. This was then implemented here:

https://github.com/dsgibbons/shap/pull/84

**Review by connortann — APPROVED** [review]
This looks great! Over to you to merge when ready.

File: pyproject.toml [hunk 1]
```diff
@@ -67,11 +67,12 @@ test = [
   "pyspark",
   "pyod",
   "transformers",
+  "tf-keras",
   "protobuf==3.20.3",  # See GH #3046
   "torch==2.2.0; sys_platform == 'darwin'",  # see GH #3524
   "torch; sys_platform != 'darwin'",
   "torchvision",
-  "tensorflow<2.16;python_version<'3.12'",  # FIXME: pending keras 3.0 support, pending tf py3.12 support
+  "tensorflow",  # pending tf py3.12 support
```
Comment (connortann) [inline pyproject.toml]: I suppose this comment is no longer relevant, as the tests pass on py 3.12.

```suggestion
  "tensorflow",
```

**Comment by CloseChoice** [comment]
@connortann Thanks for the review. Will merge on green.

**Comment by connortann** [comment]
@CloseChoice would you be able to take a look at this conda error, I think it might be related to this PR.
https://github.com/conda-forge/shap-feedstock/pull/85
