### ISSUE TITLE
Possible Compatibility Issues in PyTorchDeepExplainer (tested in PyTorch 1.0 Preview)

### ISSUE THREAD

**Issue by ceshine** [shap/shap#301]
Hi, 

I wasn't able to run PyTorchDeepExplainer in my environment, so I followed the error messages and made some changes to it. [Here are the changes](https://github.com/ceshine/shap/commit/d7ad868c9e64ef4ddfb4d746482b4bbc287f2625). (The model I trained has a single regression output.)

It's very likely that I did not fix the problem correctly, hence no PR, just an issue here as FYI. 

[Example (Kaggle Kernel)](https://www.kaggle.com/ceshine/feature-importance-from-a-pytorch-model/notebook)

The error messages were (paraphrasing):

- PyTorchDeepExplainer does not have the property `num_outputs`.
- Cannot multiply a PyTorch tensor by a numpy array.

**Comment by austinmw** [comment]
Were you able to get `PyTorch Deep Explainer MNIST example.ipynb` working with PyTorch 1.0, and if so can you please share?

**Comment by ceshine** [comment]
Yes, I was able to get it working with both PyTorch 1.0 and 0.4.1. 

* 0.4.1 (Kaggle kernel): https://www.kaggle.com/ceshine/pytorch-deep-explainer-mnist-example
* 1.0.0 (Github gist): https://gist.github.com/ceshine/37dcc304f22b0ad40b01e47c70f555ec

The version of SHAP package (0.24.0) that comes with Kaggle Kernel does not work, though: https://www.kaggle.com/ceshine/pytorch-deep-explainer-mnist-example-unmodified

**Comment by slundberg** [comment]
That's because PyTorch support is new in 0.25 which I am working to get pushed soon.

**Comment by ceshine** [comment]
Yes. The output "Using TensorFlow backend." from the 0.24.0 kernel kinda gave it away. I was trying to demonstrate a possible scenario of failure, as @austinmw did not mention whether he has successfully got the notebook runing with PyTorch 0.4.1 or not. Sorry for not being clear enough. [Here's a notebook](https://www.kaggle.com/ceshine/pytorch-deep-explainer-mnist-example-latest) confirming the notebook works with a install from the official master branch.

And here's [an example notebook](https://www.kaggle.com/ceshine/pytorch-feature-importance-official-master#) of a install from the official master branch that failed with a regression model. As I mentioned in the issue description, the error message says: `AttributeError: 'PyTorchDeepExplainer' object has no attribute 'num_outputs'`. (Edit: This can imply that the problem I had encountered is probably not a PyTorch 1.0 compatibility problem, but rather a general bug.)

**Comment by slundberg** [comment]
Thanks for sharing this! It looks like the PyTorch version of DeepExplainer is not handling single output models. I'll tag this as needing a fix. @gabrieltseng you have any thoughts on this?

**Comment by gabrieltseng** [comment]
I think I see where the problem is; I can take a look at it this weekend.
