### ISSUE TITLE
AttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'

### ISSUE THREAD

**Issue by zainabHath** [shap/shap#2189]
Hello 

I am trying to get shap_values using DeepExplainer but it keep giving this error
"AttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'"

**Comment by Yo-B** [comment]
same error here, with tf 2.6 and shap 0.40
Did you find a fix @zainabHath ?

**Comment by zainabHath** [comment]
@Yo-B  Unfortunately no, but I think that TensorFlow changed the attribute name that caused the error or replaced it. Because I already checked the override attribute in the TensorFlow GitHub, there is no attribute named "_record_gradient ".

**Comment by WanHern** [comment]
@Yo-B @zainabHath I had this error recently as well - for me it happened when I updated Tensorflow to 2.6.0, I reverted it back to 2.5.0 and that worked for me

**Comment by Yo-B** [comment]
@WanHern Interesting, thanks. Yesterday I reverted to tf 2.4 and python 3.7 in a new environment, then I also tried with tf 2.0 but all without success. I should try tf 2.5 and python 3.9 I guess, right? I'll have a look. Cheers,

**Comment by Yo-B** [comment]
@WanHern @zainabHath It indeed worked but triggered another error that could be corrected by using
`shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough`
according to this issue: https://github.com/slundberg/shap/issues/1110
That is great, thanks!

**Comment by juan-carlos-calvo** [comment]
same error with tensorflow 2.7 and python 3.8.11.
Any solutions that do not require reverting tensorflow?

**Comment by Yo-B** [comment]
@juan-carlos-calvo I haven't found any, sorry. Although I had no side effects from reverting, and shap works great!

**Comment by juan-carlos-calvo** [comment]
yeah, but I need functionality only available in the latest tensorflow version :/. I'm trying with some of the other explainers for now.

**Comment by aiqc** [comment]
given that importing keras works differently in later versions (`tf.keras`), not supporting recent tensorflow versions puts stress on the rest of the codebase

**Comment by filusn** [comment]
I tried to fix it and opened the pull request: #2355

**Comment by rozeappletree** [comment]
still happening in kaggle kerner


python version: `Python 3.7.12`

```
shap==0.40.0

tensorflow @ file:///opt/conda/conda-bld/dlenv-tf-2-6-cpu_1639877225671/work/tensorflow-2.6.2-cp37-cp37m-linux_x86_64.whl
tensorflow-addons==0.14.0
tensorflow-cloud==0.1.14
tensorflow-datasets==4.3.0
tensorflow-estimator==2.6.0
tensorflow-gcs-config==2.6.0
tensorflow-hub==0.12.0
tensorflow-io==0.21.0
tensorflow-metadata==1.5.0
tensorflow-probability==0.14.1
tensorflow-serving-api==2.7.0
tensorflow-transform==1.5.0
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_54/3488049008.py in <module>
      6 # ...or pass tensors directly
      7 # e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)
----> 8 shap_values = e.shap_values(correct[1:5])
      9 
     10 # plot the feature attributions

/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/__init__.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    122             were chosen as "top".
    123         """
--> 124         return self.explainer.shap_values(X, ranked_outputs, output_rank_order, check_additivity=check_additivity)

/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py in shap_values(self, X, ranked_outputs, output_rank_order, check_additivity)
    306                 # run attribution computation graph
    307                 feature_ind = model_output_ranks[j,i]
--> 308                 sample_phis = self.run(self.phi_symbolic(feature_ind), self.model_inputs, joint_input)
    309 
    310                 # assign the attributions to the right part of the output arrays

/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py in run(self, out, model_inputs, X)
    363 
    364                 return final_out
--> 365             return self.execute_with_overridden_gradients(anon)
    366 
    367     def custom_grad(self, op, *grads):

/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py in execute_with_overridden_gradients(self, f)
    399         # define the computation graph for the attribution values using a custom gradient-like computation
    400         try:
--> 401             out = f()
    402         finally:
    403             # reinstate the backpropagatable check

/opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py in anon()
    359                     v = tf.constant(data, dtype=self.model_inputs[i].dtype)
    360                     inputs.append(v)
--> 361                 final_out = out(inputs)
    362                 tf_execute.record_gradient = tf_backprop._record_gradient
    363 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    883 
    884       with OptionalXlaContext(self._jit_compile):
--> 885         result = self._call(*args, **kwds)
    886 
    887       new_tracing_count = self.experimental_get_tracing_count()

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    931       # This is the first call of __call__, so we have to initialize.
    932       initializers = []
--> 933       self._initialize(args, kwds, add_initializers_to=initializers)
    934     finally:
    935       # At this point we know that the initialization is complete (or less

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    758     self._concrete_stateful_fn = (
    759         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 760             *args, **kwds))
    761 
    762     def invalid_creator_scope(*unused_args, **unused_kwds):

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   3064       args, kwargs = None, None
   3065     with self._lock:
-> 3066       graph_function, _ = self._maybe_define_function(args, kwargs)
   3067     return graph_function
   3068 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3461 
   3462           self._function_cache.missed.add(call_context_key)
-> 3463           graph_function = self._create_graph_function(args, kwargs)
   3464           self._function_cache.primary[cache_key] = graph_function
   3465 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3306             arg_names=arg_names,
   3307             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3308             capture_by_value=self._capture_by_value),
   3309         self._function_attributes,
   3310         function_spec=self.function_spec,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
   1005         _, original_func = tf_decorator.unwrap(python_func)
   1006 
-> 1007       func_outputs = python_func(*func_args, **func_kwargs)
   1008 
   1009       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/opt/conda/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    666         # the function a weak reference to itself to avoid a reference cycle.
    667         with OptionalXlaContext(compile_with_xla):
--> 668           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    669         return out
    670 

/opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

AttributeError: in user code:

    /opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py:243 grad_graph  *
        out = self.model(shap_rAnD)
    /opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py:1037 __call__  **
        outputs = call_fn(inputs, *args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/keras/engine/functional.py:415 call
        inputs, training=training, mask=mask)
    /opt/conda/lib/python3.7/site-packages/keras/engine/functional.py:550 _run_internal_graph
        outputs = node.layer(*args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/keras/engine/base_layer.py:1037 __call__
        outputs = call_fn(inputs, *args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/keras/layers/convolutional.py:249 call
        outputs = self._convolution_op(inputs, self.kernel)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:206 wrapper
        return target(*args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py:1138 convolution_v2
        name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py:1268 convolution_internal
        name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/nn_ops.py:2722 _conv2d_expanded_batch
        name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_nn_ops.py:973 conv2d
        data_format=data_format, dilations=dilations, name=name)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:522 _apply_op_helper
        preferred_dtype=default_dtype)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/profiler/trace.py:163 wrapped
        return func(*args, **kwargs)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/framework/ops.py:1566 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:2023 _dense_var_to_tensor
        return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:1421 _dense_var_to_tensor
        return self.value()
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:576 value
        return self._read_variable_op()
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:683 _read_variable_op
        result = read_and_set_handle()
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py:674 read_and_set_handle
        self.handle, self._dtype)
    /opt/conda/lib/python3.7/site-packages/tensorflow/python/ops/gen_resource_variable_ops.py:491 read_variable_op
        "ReadVariableOp", _inputs_flat, _attrs, _result)
    /opt/conda/lib/python3.7/site-packages/shap/explainers/_deep/deep_tf.py:26 custom_record_gradient
        out = tf_backprop._record_gradient("shap_"+op_name, inputs, attrs, results)

    AttributeError: module 'tensorflow.python.eager.backprop' has no attribute '_record_gradient'
```

**Comment by Yo-B** [comment]
I confirm it is still happening in fresh environment tf 2.8 / python 3.10. The fix provided by @filusn seems to work though! many thanks

**Comment by kaii55** [comment]
if the latest version of TensorFlow version is installed please add the below lines - 

import tensorflow as tf
tf.compat.v1.disable_v2_behavior() 

This will solve the problem.

**Comment by ryankshah** [comment]
> if the latest version of TensorFlow version is installed please add the below lines -
> 
> import tensorflow as tf tf.compat.v1.disable_v2_behavior()
> 
> This will solve the problem.

Agreed, this solved for me! Also, you can refer to the following SO answer: https://stackoverflow.com/a/66844039/2627859

**Comment by Sihyun-An** [comment]
@kaii55 Awwwwwwwwwesome!! You're the greatest engineer.

I have gotten some weird, because there are many fraud information.

But your suggestion works very well!!

Thank you.

**Comment by synchro--** [comment]
Hi, since this has been fixed in release 0.41, shouldn't this issue be closed? @slundberg 

Otherwise this might be misleading: the fact that the issue is still open made me believe it was not fixed. Hence, I did not even bothered looking for an updated version of the package whereas in reality an easy `pip install --upgrade shap` would have sufficed.

**Comment by Yo-B** [comment]
@synchro-- I have just updated to .41 (with tf 2.8) and I still need this fix
`shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough` 
to run shap on my model. It's not inconvenient once you know about this solution, but maybe not yet fixed, right?
