### ISSUE TITLE
Trouble using DeepExplainer

### ISSUE THREAD

**Issue by PabloJabat** [shap/shap#826]
AttributeError: module 'keras.backend.tensorflow_backend' has no attribute '_SESSION'

I get this error when using a keras neural network as a model. I have checked the keras module and there is no _SESSION attribute to be found. It looks like deep_tf.py checks if there is an open tensor flow session but also cheks for this _SESSION attribute. Is it possible to fix this error?

**Comment by SkalskiP** [comment]
Hello, I have the same error. I'm trying to use the DeepExplainer on my Keras model.

**Comment by PabloJabat** [comment]
I finally figured it out. You have to downgrade your keras version to 2.2.5. The latest shap version in pip just works on keras 2.2.5

**Comment by slundberg** [comment]
This is fixed on master now :)

**Comment by shilpibhattacharyya** [comment]
Hi @slundberg ,

When I am running this code, I am getting the following error. I have tried installing/uninstalling few combinations of tensorflow/keras. Nothing seems to resolve it. Can you kindly advise? Thank you.


Error:
=========
nonlinear_mxts_mode is set to: DeepLIFT_GenomicsDefault
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-142-10363315c374> in <module>
      6     kc.convert_model_from_saved_files(
      7         'my_model.h5',
----> 8         nonlinear_mxts_mode=deeplift.layers.NonlinearMxtsMode.DeepLIFT_GenomicsDefault) 
      9 
     10 #Specify the index of the layer to compute the importance scores of.

/usr/local/lib/python3.7/site-packages/deeplift/conversion/kerasapi_conversion.py in convert_model_from_saved_files(h5_file, json_file, yaml_file, **kwargs)
    398             layer_config["config"]["weights"] = layer_weights
    399 
--> 400     return model_conversion_function(model_config=model_config, **kwargs)
    401 
    402 

/usr/local/lib/python3.7/site-packages/deeplift/conversion/kerasapi_conversion.py in convert_sequential_model(model_config, nonlinear_mxts_mode, verbose, dense_mxts_mode, conv_mxts_mode, maxpool_deeplift_mode, layer_overrides, custom_conversion_funcs)
    444     batch_input_shape = model_config[0]['config'][KerasKeys.batch_input_shape]
    445     converted_layers.append(
--> 446         layers.core.Input(batch_shape=batch_input_shape, name="input"))
    447     #converted_layers is actually mutated to be extended with the
    448     #additional layers so the assignment is not strictly necessary,

/usr/local/lib/python3.7/site-packages/deeplift/layers/core.py in __init__(self, batch_shape, **kwargs)
    199         self._num_dims = len(batch_shape)
    200         self._shape = batch_shape
--> 201         self._activation_vars = tf.placeholder(
    202                                  dtype=tf.float32, shape=batch_shape,
    203                                  name="inp_"+str(self.get_name()))

AttributeError: module 'tensorflow' has no attribute 'placeholder'

Code:
========
from tensorflow.keras.layers import Dense, Input, LSTM
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.models import load_model
import deeplift
from deeplift.conversion import kerasapi_conversion as kc

classifier = Sequential()
classifier.add(Dense(16, activation='relu', kernel_initializer='random_normal', input_dim=88))
classifier.add(Dense(8, activation='relu', kernel_initializer='random_normal'))

#Output Layer
classifier.add(Dense(1, activation='softmax', kernel_initializer='random_normal'))
#Compiling the neural network
classifier.compile(optimizer ='adam',loss='binary_crossentropy', metrics =['binary_accuracy'])
classifier.fit(X_train,Y_train, batch_size=100, epochs=5)

classifier.save('my_model.h5') 

deeplift_model =\
    kc.convert_model_from_saved_files(
        'my_model.h5',
        nonlinear_mxts_mode=deeplift.layers.NonlinearMxtsMode.DeepLIFT_GenomicsDefault) 

find_scores_layer_idx = 0

deeplift_contribs_func = deeplift_model.get_target_contribs_func(
                            find_scores_layer_idx=find_scores_layer_idx,
                            target_layer_idx=-1)

scores = np.array(deeplift_contribs_func(task_idx=0,
                                         input_data_list=[X],
                                         batch_size=10,
                                         progress_update=1000))
