### ISSUE TITLE
No module named 'shap.explainers.tree' when using SHAP with LightGBM in Azure Function

### ISSUE THREAD

**Issue by ghost** [shap/shap#1417]
Hello,

I'm getting the error after recently re-deploying an Azure function that uses SHAP.  I have a LightGBM model and a saved tree explainer that is being used.  When running the shap_values function, I get the error, "No module named 'shap.explainers.tree'.

However, when I downgrade shap to 0.35.0, the API works fine again.

Has anyone else had a similar issue?

Here is the line of code that I am running to derive the shap values:

shap_vals = shap_exp_lgb.shap_values(df[vars].astype(float))[0])

**Comment by slundberg** [comment]
There was a lot of API updates in 0.36, but they should all be backwards compatible. Can you try the master version and also see what line number is throwing that error?

**Comment by ghost** [comment]
Do you mean the number line in the Python code?  I'll give 0.36 a shot now.

**Comment by ghost** [comment]
`import shap
shap.__version__`

Returns:
`'0.36.0'`

`import joblib`
`loaded_shap_exp = joblib.load('saved_shap_exp.sav')`

Returns:
`ModuleNotFoundError...`
`ModuleNotFoundError: No module named 'shap.explainers.tree'`

Switching to shap = 0.35.0 works perfectly.

Python version = 3.7.4.

I ran this in a separate notebook and not in the Azure function API.

**Comment by ghost** [comment]
Hey Scott!  Any update on this?  I'm still grabbing the same error with 0.36.0 for some reason.  Now getting this error:
"no module named 'numba.serialize'"

**Comment by ghost** [comment]
Quick update: found that specifying the following packages in my Azure Function gave me success:

shap==0.36.0
cygrpc
llvmlite==0.32.1
numba==0.49.1

**Comment by ghost** [comment]
Hi Scott,

Do you have a suggestion on how to save a tree explainer?  I am currently saving it as a .sav and trying to load with joblib, but cannot load the model with the most current version numba due to deprecation of "serialize".

I think a quicker way to tackle the problem would save the explainer as something other than a .sav.  Any ideas?

**Comment by johnnyheineken** [comment]
We encountered the same problem.

**Comment by ghost** [comment]
John, we resolved the problem.  Happy to help.  Would you be able to give me some more background on the language you are using, some sudo code, etc.?

**Comment by grassoste** [comment]
Hi I can also confirm the bug. I also have a model from an older release and up to 0.35 everything runs smoothly, from 0.36 I get `ModuleNotFoundError: No module named 'shap.explainers.tree'`. 

Do you know any workaround to tackle this retro-compatibility issue?

**Comment by ghost** [comment]
Any chance you are using LightGBM?  We used that as a workaround but also were able to use the SHAP package.

**Comment by grassoste** [comment]
No, my model is a RandomForestRegressor from sci-kit. What workaround did you use to load it through joblib?

**Comment by ghost** [comment]
We didn't need a workaround to load it through joblib, but were getting issues when trying to run the saved explainer.  I's been  few months now, but would recommend the following (assuming your issues are also in the Azure Function API):
- Make sure your virtual environment where you are developing the app has the same version of Python where you created the explainer (my dev env. was 3.8, the API env had to be 3.8 too).  This would be the same Python runtime when the API is deployed
- Make sure your package versions in development are the same in the API in requirements.txt

Happy to help more if you are still having issues!

**Comment by grassoste** [comment]
If I use a virtual environment with the same package version of shap I have no problem. 
If I update shap from version 0.35 to 0.36 the shap.explainers is not compatible anymore. 
Of course buy doing like this is a good workaround to reproduce results and use old models, nevertheless it would be cool to use old explainers with the new functionalities. 
So I'd like to import a shap.explainer produced with shap < 0.35 into shap 0.38.

**Comment by yustiks** [comment]
i have the same error after I installed probatus library:
`ImportError: cannot import name 'Tree' from 'shap.explainers._tree' (/opt/conda/lib/python3.11/site-packages/shap/explainers/_tree.py)`

After I re-run the kernel (docker compose -down, docker compose -up), the error disappeared.

**Comment by max-franceschi** [comment]
As @yustiks I have the same error after I installed probatus library. However, restarting the kernel did not help unfortunately.

**Comment by jip333** [comment]
As @yustiks and @max-franceschi I have the same error after I updated python to 3.11. Restarting the kernel did not help and other fixes, that I tried, did not work. Could anybody help me with this.

**Comment by max-franceschi** [comment]
Unfortunately, I did not find any workaround, sorry.

**Comment by xuican** [comment]
from shap.explainers.tree import Tree    change  as      from shap import TreeExplainer as Tree
