### ISSUE TITLE
BUG: summary plot is failing in version `0.47.0` with `plot_type="violin"`

### ISSUE THREAD

**Issue by yarnabrina** [shap/shap#4030]
### Issue Description

Summary plot is not working with release of v0.47.0. This is possibly caused by #3945 by @tylerjereddy , which used `rng` which gets overriden by an existing variable `rng` calculating the range.

### Minimal Reproducible Example

```python
from shap import TreeExplainer, summary_plot
from sklearn.datasets import make_regression
from sklearn.ensemble import RandomForestRegressor

X, y = make_regression(n_features=4, n_informative=2, random_state=0, shuffle=False)

regr = RandomForestRegressor(max_depth=2, random_state=0)
_ = regr.fit(X, y)

explainer = TreeExplainer(regr)
shap_values = explainer.shap_values(X, y=y)
summary_plot(shap_values, features=X, plot_type="violin")
```

### Traceback

```shell
Traceback (most recent call last):
  File "/path/to/bug_report.py", line 13, in <module>
    summary_plot(shap_values, features=X, plot_type="violin")
  File "/path/to/venv/lib/python3.10/site-packages/shap/plots/_beeswarm.py", line 898, in summary_legacy
    tmp_y = rng.standard_normal(len(shaps))
AttributeError: 'numpy.float64' object has no attribute 'standard_normal'
```

### Expected Behavior

I expect the plot to be created

### Bug report checklist

- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [x] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [x] I'd be interested in making a PR to fix this bug

### Installed Versions

0.47.0

**Comment by tylerjereddy** [comment]
@CloseChoice I'll try to take a look this weekend.

**Comment by CloseChoice** [comment]
@yarnabrina Thanks for the report and the fantastic minimal reproducible example. I appreciate it.

@tylerjereddy thanks a lot and no worries, I already got a fix. The problem was a variable named `rng`.
