### ISSUE TITLE
BUG: Cannot import `shap.benchmark` with shap==0.42.0

### ISSUE THREAD

**Issue by natsukium** [shap/shap#3075]
### Issue Description

When I tried to import `shap.benchmark` with shap==0.42.0, I got the following ImportError.

```
ImportError: cannot import name 'BenchmarkResult' from partially initialized module 'shap.benchmark' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/shap/benchmark/__init__.py)
```

It seems that the import order changed by [this commit](https://github.com/slundberg/shap/commit/6be5b996cc7f048bf04875a8dc7775b2233dbeb4) causes the above error, which was resolved when I modified the order to import first the `BenchmarkResult`.

I have confirmed that it works fine in 0.41.0.

### Minimal Reproducible Example

```python
import shap.benchmark
```

### Expected Behavior

We can import `shap.benchmark` without the above error.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.0

**Comment by natsukium** [comment]
Thanks for the quick fix!
