### ISSUE TITLE
TFDeepExplainer broken with TF2.1.0

### ISSUE THREAD

**Issue by FRUEHNI1** [shap/shap#1055]
Hi,

With the latest HEAD revision of shap from git and TF 2.1.0 I get the following errors.

1.) **custom_record_gradient() missing 1 required positional argument: 'name'**
I assume this is due to the way the custom gradient record is defined between shap and tensorflow.
If it's not used, this would be a simple fix by either removing the argument, or setting it to None per default?

See also https://github.com/tensorflow/tensorflow/commit/6d8eafa78834e197a04086a928d9bb3e1339a9aa 

```
    TypeError: custom_record_gradient() missing 1 required positional argument: 'name'
```

If I fix this, I get:

2.)     **AttributeError: 'TFDeepExplainer' object has no attribute 'between_tensors'**
```
 out[i] = t.name in self.between_tensors
    AttributeError: 'TFDeepExplainer' object has no attribute 'between_tensors'
```
This is due to the fact that in deep_tf#L236 init_between_tensors is called, but it is expected to be there in deep_tf#L232

**Comment by forough71** [comment]
I have the exact same problem.

**Comment by MathiesW** [comment]
I am getting the same error with SHAP 0.35 and TF2.1.0

**Comment by talipini** [comment]
I am having the same issue with nightly and 2.2.0rc4. I am using SHAP 0.35. Is there any version TF that works with SHAP DeepExplainer?

**Comment by MathiesW** [comment]
I figured that shap deep explainer works with TensorFlow 1.15. I set up a virtual Python environment to calculate the shapley values and export them as numpy arrays. It's not comfortable but works well enough as a workaround.

**Comment by talipini** [comment]
Great, Thanks MathiesW.  I will try that. 
FYI, 2.1.0rc0 seems to work and is not failing with this error. but I am still trying to get everything together and test it.

**Comment by MathiesW** [comment]
Glad I could help. I just tried TensorFlow 2.1.0-rc0 but it resulted in the following error message:
`RecursionError: maximum recursion depth exceeded in comparison`

**Comment by threadgoldc** [comment]
Also the same problem

**Comment by threadgoldc** [comment]
> I figured that shap deep explainer works with TensorFlow 1.15. I set up a virtual Python environment to calculate the shapley values and export them as numpy arrays. It's not comfortable but works well enough as a workaround.

thanks. Worked for me :)

**Comment by qemtek** [comment]
The same problem exists in tensorflow 2.1.1

**Comment by jonathanglima** [comment]
Same problem in TF 2.2

**Comment by darien-schettler** [comment]
The same problem exists when using the nightly build as of July 21, 2020 -- **2.4.0-dev20200721**

**Comment by GlorianY** [comment]
The same problem exists in TF 2.3.0

**Comment by mattnorel** [comment]
I know it's not a solution but setting `tf.compat.v1.disable_v2_behavior()` right after importing tensorflow seems to work with shap's DeepExplainer. It might be a way for someone who don't want to install previous version.

**Comment by talipini** [comment]
I got a strange error when I disable v2_behavior. shap_values throws a value error with the 2x batchsize of the actual batch size in the model. My sample data is exactly the batch size of 1024. I guess SHAP is doubling the batchsize? 

ValueError: Cannot feed value of shape (2048, 124, 257) for Tensor '0_lstm_layer_input:0', which has shape '(1024, 124, 257)'

**Comment by chetanambi** [comment]
@slundberg Could you be able to confirm if versions of SHAP and tensorflow >2.0 are not compatible for explaining deep learning models? DeepExplainer, GradientExplainer or KernelExplainer not working currently. Really appreciate your guidance on this issue.

**Comment by uebenes** [comment]
I can confirm, that I have the same problem with Tensorflow 2.8 and SHAP 0.41.0
The problem only occurs with LSTM Layers - with Dense Layers the DeepExplainer works fine.

**Comment by mattfergoda** [comment]
> I can confirm, that I have the same problem with Tensorflow 2.8 and SHAP 0.41.0 The problem only occurs with LSTM Layers - with Dense Layers the DeepExplainer works fine.

I'm also still getting the `AttributeError`: 
```
Exception encountered when calling layer 'lstm' (type LSTM).
    
    'TFDeep' object has no attribute 'between_tensors'
```
with Tensorflow 2.11.0 and SHAP 0.41.0
