### ISSUE TITLE
Fixing builds on recent OS X systems

### ISSUE THREAD

**Issue by slundberg** [shap/shap#343]
If you get an error building shap on a recent OS X machine like:

`shap/tree_shap.h:8:10: fatal error: 'algorithm' file not found`

...then you should do something similar to:

```
CFLAGS="-stdlib=libc++" python setup.py install
```

**Comment by slundberg** [comment]
Note this is an issue with how setup.py works on 10.14...
