### ISSUE TITLE
Gradient Explainer; LookupError: gradient registry has no entry for: shap_StridedSlice

### ISSUE THREAD

**Issue by skomatin** [shap/shap#1406]
I am running the following code:

```
import shap 

explainer = shap.GradientExplainer(model, x_train)
shap_values = explainer.shap_values(x_test[:10])
```

I run into the following error:
```
LookupError: gradient registry has no entry for: shap_StridedSlice
```
Here is a summary of my model:
```
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
simple_rnn_6 (SimpleRNN)     (None, 10, 1)             12        
_________________________________________________________________
dense_6 (Dense)              (None, 10, 1)             2         
_________________________________________________________________
flatten (Flatten)            (None, 10)                0         
=================================================================
Total params: 14
Trainable params: 14
Non-trainable params: 0
_________________________________________________________________
```
My SHAP and TensorFlow versions are

* **shap**: 0.35.0
* **tensorflow**: 2.3.0

[Error log](https://gist.github.com/skomatin/82a41f273277807fcbeecfe1632ac23c)

**Comment by lu-victor** [comment]
I'm getting the exact same error. Have you managed to solve it?

**Comment by slundberg** [comment]
I wonder if this is new with TF 2.3, could you try on 2.2 or 2.1 and see if the same issue happens?

**Comment by patricksferraz** [comment]
Similar error here with __DeepExplainer__:

```py
import shap

background = x_train[np.random.choice(x_train.shape[0], 100, replace=False)]
e = shap.DeepExplainer(model, background )
shap_values = e.shap_values(x_test[:10])
```

Error:

```
LookupError: gradient registry has no entry for: shap_Softsign
```

Summary:

```
Model: "mlp"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
dense (Dense)                (None, 51)                969       
_________________________________________________________________
dense_1 (Dense)              (None, 88)                4576      
_________________________________________________________________
dense_2 (Dense)              (None, 76)                6764      
_________________________________________________________________
dense_3 (Dense)              (None, 51)                3927      
_________________________________________________________________
dense_4 (Dense)              (None, 2)                 104       
=================================================================
Total params: 16,340
Trainable params: 16,340
Non-trainable params: 0
_________________________________________________________________
```

__shap__: 0.35.0
__tensorflow__: 2.2.0

**Comment by skomatin** [comment]
@slundberg After changing my model structure a bit, I don't get that error anymore. Here is my new model summary:
```
Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
=================================================================
simple_rnn_4 (SimpleRNN)     (None, 607, 1)            12        
_________________________________________________________________
flatten_4 (Flatten)          (None, 607)               0         
_________________________________________________________________
dense_4 (Dense)              (None, 607)               369056    
=================================================================
Total params: 369,068
Trainable params: 369,068
Non-trainable params: 0
_________________________________________________________________
```

Note that the flatten layer was moved to before the dense layer. 

@patricksferraz I don't think DeepExplainer is supported in TF2

**Comment by keyur-potdar** [comment]
> I wonder if this is new with TF 2.3, could you try on 2.2 or 2.1 and see if the same issue happens?

Tried with TF 2.2.0 and SHAP 0.35.0, same issue.

**Comment by blanpa** [comment]
Same issue :/

**Comment by a-berg** [comment]
Same issue, using shap 0.37 (installed with pip) and Tensorflow 2.1.0. I think this worked correctly when using shap 0.36 (installed with conda).

Confirmed, it works in 0.36.

**Comment by rezahay** [comment]
Hi all,
I'm using a Keras model containing conv1, dropout, batchNormalization, flatten, and timedistributed layers. I tried DeepExplainer in the following different configurations:
- TF-2.1 and shap-0.35, shap-0.37, shap-039 (got: LookupError: gradient registry has no entry for: shap_AddV2)
- TF-2.3 and shap-0.35, shap-0.37, shap-039 (got: LookupError: gradient registry has no entry for: shap_AddV2)
- Adding this statement doesn't work and I get again a new lookupError:
 shap.explainers._deep.deep_tf.op_handlers["AddV2",'shap_Neg','shap_AddV2'] = shap.explainers._deep.deep_tf.passthrough
- TF-2.1 and shap-0.36 (I don't get immediately the LookupError and it seems to work but after some while I get the same LookupError appears)

Is there any solution?
Best Regards

**Comment by Neihtq** [comment]
Also have this error `LookupError: gradient registry has no entry for: shap_StridedSlice` when using GradientExplainer. Currently on TF-2.4.1 and shap-0.39.

**Comment by aimanakheel** [comment]
+1 facing the same issue

**Comment by mmtrebuchet** [comment]
I'm still running into this problem. I'm now on TF 2.8 and Shap 0.40, though in my case the problem entry is shap_AddV2 . 
What's the cause of this? Is it something that's easily fixable?

**Comment by TengHoo3** [comment]
@mmtrebuchet I was able to run my ResNet model (without BatchNorm layers) by adding two of the code lines below before running your SHAP DeepExplainer, not sure what implications this will have on the result but it runs properly:

TF Version - 2.8
Shap Version - 0.40

shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem but another one will appear
shap.explainers._deep.deep_tf.op_handlers["FusedBatchNormV3"] = shap.explainers._deep.deep_tf.passthrough #this solves the next problem which allows you to run the DeepExplainer.
e = shap.DeepExplainer(model, images)

**Comment by nikunj-taneja** [comment]
@mmtrebuchet @TengHoo3 I've been getting the same error and tried adding the passthrough entry for `AddV2` in the `op_handlers` (and for any subsequent errors) but still couldn't get it to work. Any idea what's causing this? I dug into the code for `DeepExplainer` a bit and found that the function which is supposed to return/populate the gradients returns a list of `None` but that's as far as I could get. I'm on tf 2.7.0 and shap 0.41.0.

**Comment by TengHoo3** [comment]
@nikunj-taneja You can try using the same version of TF and SHAP as me to see whether it works, might be a version issue. Are you getting the same error as above or is it a different error?

**Comment by anejad** [comment]
> @mmtrebuchet I was able to run my ResNet model (without BatchNorm layers) by adding two of the code lines below before running your SHAP DeepExplainer, not sure what implications this will have on the result but it runs properly:
> 
> TF Version - 2.8 Shap Version - 0.40
> 
> shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem but another one will appear shap.explainers._deep.deep_tf.op_handlers["FusedBatchNormV3"] = shap.explainers._deep.deep_tf.passthrough #this solves the next problem which allows you to run the DeepExplainer. e = shap.DeepExplainer(model, images)

I had same exact problem, and your solution worked. Thank you!

**Comment by JulianKlug** [comment]
For me this particular set of versions works fine:

- TensorFlow 1.14
- Python 3.7
- Protobuf 3.20
- h5py 2.10

```python
import tensorflow as tf
import sys
import google.protobuf
import h5py

assert tf.__version__ == '1.14.0'
assert sys.version_info[0] == 3 and sys.version_info[1] == 7
assert google.protobuf.__version__ == '3.20.0'
assert h5py.__version__ == '2.10.0'
```

**Comment by StorywithLove** [comment]
> Same issue, using shap 0.37 (installed with pip) and Tensorflow 2.1.0. I think this worked correctly when using shap 0.36 (installed with conda).
> 
> Confirmed, it works in 0.36.

Great！Same issue with shap 0.41.0 and Tensorflow 2.11.0. When using shap 0.36, it works

**Comment by PabloOlivaresUV** [comment]
> > Same issue, using shap 0.37 (installed with pip) and Tensorflow 2.1.0. I think this worked correctly when using shap 0.36 (installed with conda).
> > Confirmed, it works in 0.36.
> 
> Great！Same issue with shap 0.41.0 and Tensorflow 2.11.0. When using shap 0.36, it works

Now i have a neeew issue AttributeError: 'KerasTensor' object has no attribute 'graph' :((((((((((((((((((((((((((((

**Comment by dsgibbons** [comment]
Can you please add a minimal example in a formatted code block @PabloOlivaresUV?

**Comment by jintiandefanzhenhaochi** [comment]
> @mmtrebuchet I was able to run my ResNet model (without BatchNorm layers) by adding two of the code lines below before running your SHAP DeepExplainer, not sure what implications this will have on the result but it runs properly:
> 
> TF Version - 2.8 Shap Version - 0.40
> 
> shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem but another one will appear shap.explainers._deep.deep_tf.op_handlers["FusedBatchNormV3"] = shap.explainers._deep.deep_tf.passthrough #this solves the next problem which allows you to run the DeepExplainer. e = shap.DeepExplainer(model, images)

I tried this , then there is a new question

>  The SHAP explanations do not sum up to the model's output! This is either because of a rounding error or because an operator in your computation graph was not fully supported. 

I guess this question is caused by the passthrough operation. I feel sad .QAQ

**Comment by samma98** [comment]
> > @mmtrebuchet I was able to run my ResNet model (without BatchNorm layers) by adding two of the code lines below before running your SHAP DeepExplainer, not sure what implications this will have on the result but it runs properly:
> > TF Version - 2.8 Shap Version - 0.40
> > shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem but another one will appear shap.explainers._deep.deep_tf.op_handlers["FusedBatchNormV3"] = shap.explainers._deep.deep_tf.passthrough #this solves the next problem which allows you to run the DeepExplainer. e = shap.DeepExplainer(model, images)
> 
> I had same exact problem, and your solution worked. Thank you!

I am running a EfficientNetB0. First met with this issue and got it resolved. Then, another error comes. 
gradient registry has no entry for: shap_DepthwiseConv2dNative

**Comment by HaneenSu** [comment]
@samma98 were you able to resolve this error: LookupError: gradient registry has no entry for: shap_DepthwiseConv2dNative ? I am facing the same error with my model that indeed has a DepthwiseConv2d layer in it.

**Comment by sunnivaf** [comment]
@HaneenSu Did you work it out? I am experiencing the same.

**Comment by samma98** [comment]
Hi @HaneenSu , @sunnivaf , yes i managed to fix it. Use this code:

pip install shap

import shap
import numpy as np
import tensorflow as tf

# Load the Deep Learning model
model = m

# Create a representative dataset 
def create_representative_dataset(dataflow, num_samples=100):
    X = []
    for _ in range(num_samples):
        imgs, _ = dataflow.next()
        for img in imgs:
            X.append(img)
            if len(X) == num_samples:
                return np.array(X)
    return np.array(X)

representative_data = create_representative_dataset(dataflowtraining)

# Initialize SHAP explainer
explainer = shap.GradientExplainer(model, representative_data)

# Compute SHAP values
shap_values = explainer.shap_values(image) #preprocess the image according to the requirement of the Deep Learning model

# Visualize the explanation
shap.image_plot(shap_values, -image)

**Comment by HaneenSu** [comment]
@samma98 Thanks for sharing! Which versions of tensorflow and keras you used?

**Comment by vojtech-filipec** [comment]
@TengHoo3 Thank you for your hint - the issue still persists (May 2024) yet your first line of code was sufficient for me to work it out: 
```
shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem 
e = shap.DeepExplainer(model, images)
```

For reference: 
tensorflow-cpu                    2.11.0
shap                                     0.45.1

**Comment by vojtech-filipec** [comment]
@TengHoo3 Thank you for your hint - the issue still persists (May 2024) yet your first line of code was sufficient for me to work it out: 
```
shap.explainers._deep.deep_tf.op_handlers["AddV2"] = shap.explainers._deep.deep_tf.passthrough #this solves the "shap_ADDV2" problem 
e = shap.DeepExplainer(model, images)
```

For reference: 
tensorflow-cpu                    2.11.0
shap                                     0.45.1

**Comment by LoVaKo** [comment]
I ran into this issue too. What solved it for me was changing out the GlobalAveragePooling2D layer for a Flatten layer in the model. I only trained it for 1 epoch though. I'm fully retraining it right now, to check for the difference in results, and to see if shap is still okay with this.. I'm very curious as to how this makes a difference though.

I could also fix it with a passthrough but I'm not certain as to how this will affect the results.
