### ISSUE TITLE
How to use explainer for MLPRegressor model

### ISSUE THREAD

**Issue by sukrit2013** [shap/shap#2136]
I have an MLPRegressor model. I want to interpret the results using SHAP.

I tried the following:
import shap
shap.initjs()

explainer = shap.KernelExplainer(mlpreg2.predict_proba, trainX, link="logit")
shap_values = explainer.shap_values(testX, nsamples=100)

shap.force_plot(explainer.expected_value[0], shap_values[0][0,:], testX.iloc[0,:], link="logit")

Error: 'MLPRegressor' object has no attribute 'predict_proba'

I also tried the following:
explainer = shap.LinearExplainer(mlpreg2, trainX, feature_dependence="independent")
shap_values = explainer.shap_values(testX)
X_test_array = testX.toarray() 

Error: An unknown model type was passed: <class 'sklearn.neural_network.multilayer_perceptron.MLPRegressor'>

Can we use SHAP to do an interpretation of the MLPRegressor model? If not, what types of model architecture are supported by SHAP?

**Comment by thecml** [comment]
Considering you're doing regression, calling `predict_proba()` doesn't really make sense here. Try something like this (worked with scikit-learn 0.24.1 and shap 0.37.0):

```
import shap
from sklearn.neural_network import MLPRegressor
from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split

X, y = make_regression(n_samples=200, random_state=1)
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    random_state=1)
regr = MLPRegressor(random_state=1, max_iter=500).fit(X_train, y_train)
print(regr.predict(X_test[:2]))
print(regr.score(X_test, y_test))

explainer = shap.KernelExplainer(model=regr.predict, data=X_train, link="identity")
shap_values = explainer.shap_values(X_test, nsamples=100)

shap.initjs()
shap.force_plot(explainer.expected_value, shap_values[0], X_test[:1])
```
Hope it helps!

**Comment by zyb1123** [comment]
ueError: <class 'sklearn.neural_network._multilayer_perceptron.MLPRegressor'> is not currently a supported model type!

**Comment by zyb1123** [comment]
How to resolve this problem？？
