### PR TITLE
Fix benchmark top-level import

### LINKED ISSUE #3075: BUG: Cannot import `shap.benchmark` with shap==0.42.0
### Issue Description

When I tried to import `shap.benchmark` with shap==0.42.0, I got the following ImportError.

```
ImportError: cannot import name 'BenchmarkResult' from partially initialized module 'shap.benchmark' (most likely due to a circular import) (/usr/local/lib/python3.10/site-packages/shap/benchmark/__init__.py)
```

It seems that the import order changed by [this commit](https://github.com/slundberg/shap/commit/6be5b996cc7f048bf04875a8dc7775b2233dbeb4) causes the above error, which was resolved when I modified the order to import first the `BenchmarkResult`.

I have confirmed that it works fine in 0.41.0.

### Minimal Reproducible Example

```python
import shap.benchmark
```

### Expected Behavior

We can import `shap.benchmark` without the above error.

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/slundberg/shap/releases) of shap.
- [X] I have confirmed this bug exists on the [master branch](https://github.com/slundberg/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [X] I'd be interested in making a PR to fix this bug

### Installed Versions

0.42.0

### PR DESCRIPTION
**Pull request by thatlittleboy**
## Overview

Description of the changes proposed in this pull request:

- Changed the import of the files within `shap/benchmark/` to be direct imports instead of importing from the `__init__.py` file.

I've tried `import shap.benchmark` locally and can verify the reported issue in #3075 is fixed.

### Note 

I thought about fixing our tests alongside this PR.  
Right now, the `tests/benchmark/*.py` aren't being collected by pytest because the filenames are not prefixed by `test_`. But the tests themselves are using a somewhat broken API, e.g. `framework` needs to be imported in `benchmark/__init__.py`, and the `SequentialPerturbation()` doesn't have a `model_score` method, etc. 

The fixes there are non-trivial and possibly involve public API changes, so I think we should leave that to a separate PR.

## Checklist

- [X] Closes #3075 
- [X] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [x] Unit tests added (if fixing a bug or adding a new feature)
- [X] Added entry to `CHANGELOG.md` (if changes will affect users)

### CODE REVIEW

**Comment by connortann** [comment]
An optional suggestion, at a pinch it could be useful to add a very minimal test to confirm the import works, such as:

```python
# tests/benchmark/test_import.py
def test_import():
    import shap.benchmark
```

As you say, it would be great to get the other benchmark tests working in future.

**Review by connortann — APPROVED** [review]
LGTM, with one suggestion. Over to you to merge
