### ISSUE TITLE
BUG: shap.plots.bar(shap_values) TypeError

### ISSUE THREAD

**Issue by JeroenWalchenbach** [shap/shap#3673]
### Issue Description

when using barplot function from shap a TypeError occurs when calling line 260 ax.set_yticks. 

set_ticks has no attribute fontsize. 

### Minimal Reproducible Example

```python
import shap 
shap.initjs()

model = xg.XGBRegressor()
model.fit(X_train, y_train)
explainer = shap.Explainer(model)
shap_values = explainer(X_train)

shap.plots.bar(shap_values)
```

### Traceback

```shell
Traceback (most recent call last)
/var/folders/pk/yjvh2jtj15ldhmcxb6_ss_ch0000gn/T/ipykernel_11569/768057057.py in <module>
----> 1 shap.plots.bar(shap_values, ax=None)

/opt/anaconda3/lib/python3.9/site-packages/shap/plots/_bar.py in bar(shap_values, max_display, order, clustering, clustering_cutoff, show_data, ax, show)
    258 
    259     # draw the yticks (the 1e-8 is so matplotlib 3.3 doesn't try and collapse the ticks)
--> 260     ax.set_yticks(list(y_pos) + list(y_pos + 1e-8), yticklabels + [t.split('=')[-1] for t in yticklabels], fontsize=13)
    261 
    262     xlen = ax.get_xlim()[1] - ax.get_xlim()[0]

/opt/anaconda3/lib/python3.9/site-packages/matplotlib/axes/_base.py in wrapper(self, *args, **kwargs)
     71 
     72         def wrapper(self, *args, **kwargs):
---> 73             return get_method(self)(*args, **kwargs)
     74 
     75         wrapper.__module__ = owner.__module__

TypeError: set_ticks() got an unexpected keyword argument 'fontsize'
```

### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest release](https://github.com/shap/shap/releases) of shap.
- [ ] I have confirmed this bug exists on the [master branch](https://github.com/shap/shap/blob/master/CONTRIBUTING.md#installing-from-the-master-branch) of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Installed Versions

0.45.1

**Comment by thatlittleboy** [comment]
hi @JeroenWalchenbach , your example is not reproducible. (`X_train`, `y_train` are not defined).

This works, for example:

```python
import shap
import xgboost as xg
shap.initjs()

X_train, y_train = shap.datasets.adult(n_points=500)
model = xg.XGBRegressor()
model.fit(X_train, y_train)
explainer = shap.Explainer(model)
shap_values = explainer(X_train)

shap.plots.bar(shap_values)
```

So it probably has something to do with how your data is defined.

**Comment by ibe-314** [comment]
@thatlittleboy: I had the same error message as @JeroenWalchenbach. In my case it was due to the matplotlib version I used. After upgrading it worked.

With matplotlib-3.3.4 I get the error above ("TypeError: set_ticks() got an unexpected keyword argument 'fontsize'") and with matplotlib-3.9.2 it works. I guess, matplotlib changed it set_ticks() method, so in older version there is no keyword argument "fontsize" but in newer there is. I have not checked the minimum matplotlib version for which shap.plots.bar(...) works.

I would suggest to add a minimum matplotlib version to the requirements in pyproject.toml.

**Comment by ibe-314** [comment]
I tested the example from @thatlittleboy 

```
import shap
import xgboost as xg
shap.initjs()

X_train, y_train = shap.datasets.adult(n_points=500)
model = xg.XGBRegressor()
model.fit(X_train, y_train)
explainer = shap.Explainer(model)
shap_values = explainer(X_train)

shap.plots.bar(shap_values)
```

on different Matplotlib versions. It works with matplotlib >= 3.5.0 and with <3.5.0 it does not work.

**Comment by achraf110** [comment]
Before plotting, explicitly turn off minor y‑ticks and reset plotting defaults:

```
import matplotlib.pyplot as plt
plt.rcParams['ytick.minor.visible'] = False
plt.rcdefaults()
```

This directly addresses the known `ytick.minor.visible` memory blow‑up.

**Comment by ashwinkothavade** [comment]
This bug still reproduces on current master — the offending line has moved but is unchanged: [`shap/plots/_bar.py:277`](https://github.com/shap/shap/blob/master/shap/plots/_bar.py#L277):

```python
ax.set_yticks(list(y_pos) + list(y_pos + 1e-8), yticklabels + [t.split("=")[-1] for t in yticklabels], fontsize=13)
```

@ibe-314's analysis is right: matplotlib 3.5.0 (Nov 2021) added `**kwargs` text-property passthrough to `Axes.set_ticks`. Before that, `fontsize=` is a `TypeError`. `matplotlib` is currently unpinned in `pyproject.toml`, so users on matplotlib < 3.5 will still hit this.

I'd like to take this on as part of my European Summer of Code 2026 application. Two possible fixes:

1. **Refactor the call** — split the font size out:
   ```python
   ax.set_yticks(list(y_pos) + list(y_pos + 1e-8), yticklabels + [t.split("=")[-1] for t in yticklabels])
   ax.tick_params(axis="y", labelsize=13)
   ```
   Works on every matplotlib version, zero impact on users on 3.5+.

2. **Pin matplotlib >= 3.5.0** in `pyproject.toml`. Per SPEC 0 that's already in the acceptable-to-drop window (3.5 is > 2 years old), but it's a policy decision that affects more than this bug.

I'd propose (1) for this PR — it's the minimal, no-policy-decision fix — and happy to open a separate issue/PR for (2) if maintainers want to follow up on the dep pin.

Plan:
- fix the line above
- add a regression test in `tests/plots/` that runs `shap.plots.bar(shap_values)` end-to-end (the existing test suite covers the function but not the yticks path specifically) and asserts no exception
- confirm locally the test passes

Side note: @achraf110 — I think your comment may belong on #4061 (the `ytick.minor.visible` OOM issue) rather than here; this issue is about a different `TypeError` on older matplotlib.

Targeting a draft PR within 2 days.
