### ISSUE TITLE
BUG: not compatible with numpy 1.24.3 (does shap fix any of its requirements?)

### ISSUE THREAD

**Issue by patricksheehan** [shap/shap#2992]
### Bug report checklist

- [X] I have checked that this issue has not already been reported.
- [X] I have confirmed this bug exists on the [latest version](https://github.com/slundberg/shap/releases) of shap.

- [X] I have confirmed this bug exists on the master branch of shap.
- [ ] I'd be interested in making a PR to fix this bug

### Minimal Reproducible Example

```python
tree explainer with xgboost with numpy at version 1.24.3
```

### Issue Description

Looks like shap does not work with numpy 1.24.3:

```
(<class 'AttributeError'>, AttributeError("module 'numpy' has no attribute 'int'.\n`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.\nThe aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:\n    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations"), <traceback object at 0x14a8d7440>)
```

As a side note, I LOVE this package, shap is great. I have, however, experienced that this package almost never works on fresh install anytime I pick it up. And it seems because there are hidden assumptions about what version of the underlying packages used should be. Isn't it common practice to put these requirements in requirements.txt or something similar? Could shap fix it's requirement versions so I don't have to do this discovery work as a user?

### Expected Behavior

That you can run the thing

### Installed Versions

0.41.0

**Comment by dsgibbons** [comment]
Fixed by #2943

**Comment by dsgibbons** [comment]
@patricksheehan you can get a working version via `pip install git...` or you can wait for 0.42 to be released.
