### ISSUE TITLE
numpy 1.16.4 not supported due to scikit-image use of _validate_lengths in versions below 0.15!

### ISSUE THREAD

**Issue by shsab** [shap/shap#731]
SHAP is not working with numpy 1.16.4 due to the removal of the _validate_lengths in the new numpy. 
I have upgraded the scikit-image and it is working! So probably should enforce the scikit-image version.

Here is the error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/shap/__init__.py", line 11, in <module>
    from .plots.summary import summary_plot
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/shap/plots/summary.py", line 15, in <module>
    from . import colors
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/shap/plots/colors.py", line 7, in <module>
    import skimage.color
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/skimage/__init__.py", line 157, in <module>
    from .util.dtype import *
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/skimage/util/__init__.py", line 8, in <module>
    from .arraycrop import crop
  File "/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/skimage/util/arraycrop.py", line 8, in <module>
    from numpy.lib.arraypad import _validate_lengths
ImportError: cannot import name '_validate_lengths' from 'numpy.lib.arraypad' (/home/ssabzevari/anaconda3/envs/test/lib/python3.7/site-packages/numpy/lib/arraypad.py)

**Comment by slundberg** [comment]
Thanks! This looks like an issue with skimage. skimage is only used for color scale transforms so we might be able to drop the need for it

**Comment by detrin** [comment]
@dsgibbons Candidate for closing.
