### ISSUE TITLE
TypeError: get_backward_walk_ops() got an unexpected keyword argument 'within_ops_fn'

### ISSUE THREAD

**Issue by NTNguyen13** [shap/shap#164]
I tried to replicate the MNIST Example from readme.md. The first part is the code from https://github.com/keras-team/keras/blob/master/examples/mnist_cnn.py, and the later part is from readme.md
When I tried
`e = shap.DeepExplainer((model.layers[0].input, model.layers[-1].output), background)`
or
`e = shap.DeepExplainer(model, background)`

it has the notice: 

Traceback (most recent call last):
  File "/home/cngc3/anaconda3/envs/tensorflow/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-11-55bf3cfb6050>", line 1, in <module>
    e = shap.DeepExplainer(model, background)
  File "/home/cngc3/anaconda3/envs/tensorflow/lib/python3.6/site-packages/shap/explainers/deep.py", line 143, in __init__
    within_ops_fn=lambda op: op.type not in DeepExplainer.dependence_breakers
TypeError: get_backward_walk_ops() got an unexpected keyword argument 'within_ops_fn'

**Comment by slundberg** [comment]
That happens with older versions of TensorFlow. It works on 1.8, not sure
about before that.

**Comment by NTNguyen13** [comment]
@slundberg I have updated tensorflow and tensorflow-base from 1.7.0 to 1.8.0 and it works.

P/s: it may off-topic but I also wonder about the difference between MNIST example and VGG16 example. While in MNIST example, the syntax is background randomly select from dataset and model, the latter one uses some sort of function with np.zeroes.
I have a convolutional network, I tried to follow the VGG16 example but I'm unable to derive this type of graph(stuck at the define the function f step)
https://raw.githubusercontent.com/slundberg/shap/master/docs/artwork/strawberry_example.png

**Comment by slundberg** [comment]
Great! I am posting a new DeepExplainer/GradientExplainer VGG16 example
tomorrow. I’ll post here when I do.

**Comment by NTNguyen13** [comment]
Thank you very much! A small suggestion from me that some built-in function for keras.application, such as `preprocess_input`, `decode_predictions` should not be used, using `probas_to_classes()` or some functions from keras.utils is better for generalization.

Thank you again.
