### ISSUE TITLE
SHAP not working in Python 3.7.6

### ISSUE THREAD

**Issue by tmbluth** [shap/shap#1021]
I just upgraded to Python 3.7.6 from 3.7.3 and SHAP stopped working. I then went to update SHAP to version 0.34.0 and it is still not loading. It gets an import error:

cannot import name 'safe_isinstance' from 'shap.common' (C:\ProgramData\Anaconda3\lib\site-packages\shap\common.py)

Is SHAP not supported beyond Python 3.7.3?

**Comment by slundberg** [comment]
Hmm..I can't imagine why that change would cause a problem. I am using 3.7.4 myself without issue. Could you try reinstalling or cloning master?

**Comment by maerzm** [comment]
I am getting this error: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key
as reported hiere: https://github.com/tensorflow/probability/issues/540
I have updated to TF 2.1 and TFP 0.9.
On that side the problems have been adressed using shap (among others), and upgrading seems a solltion but not with shap… any idea?

**Comment by kokliang** [comment]
#from shap.common import safe_isinstance, format_value
from .. import common

commented original codes above & import the whole common module seems ok

**Comment by deb294** [comment]
> I am getting this error: Tensor is unhashable if Tensor equality is enabled. Instead, use tensor.experimental_ref() as the key
> as reported hiere: [tensorflow/probability#540](https://github.com/tensorflow/probability/issues/540)
> I have updated to TF 2.1 and TFP 0.9.
> On that side the problems have been adressed using shap (among others), and upgrading seems a solltion but not with shap… any idea?

hi, I'm facing this same problem while ruuning tutoial code. 
 # make model predictions
     22 e = shap.GradientExplainer((model.layers[7].input, model.layers[-1].output), 
---> 23                             map2layer(preprocess_input(X.copy()), 7)) 
     24 shap_values, indexes = e.shap_values(map2layer(to_predict, 7), ranked_outputs=2)
     25 index_names = np.vectorize(lambda x: class_names[str(x)][1])(indexes)
did you find the solutions ?

**Comment by maciejskorski** [comment]
> I just upgraded to Python 3.7.6 from 3.7.3 and SHAP stopped working. I then went to update SHAP to version 0.34.0 and it is still not loading. It gets an import error:
> 
> cannot import name 'safe_isinstance' from 'shap.common' (C:\ProgramData\Anaconda3\lib\site-packages\shap\common.py)
> 
> Is SHAP not supported beyond Python 3.7.3?

Note that the shap repo got restructured and `shap.common` may not work in recent releases. 
For my legacy code, I use `pip install shap==0.23.0`
